### PR TITLE
fix(tests): Remove beacon root contract from state tests

### PR DESCRIPTION
**Pull request by marioevz**
## 🗒️ Description
Removes the beacon root contract and its execution outcome from the state tests by separating the fork pre-alloc by blockchain and non-blockchain tests.

Also converts the beacon root contract tests to blockchain tests.

## 🔗 Related Issues
#446

## ✅ Checklist
- [x] All: Set appropriate labels for the changes.
- [x] All: Considered squashing commits to improve commit history.
- [x] All: Added an entry to [CHANGELOG.md](/ethereum/execution-spec-tests/blob/main/docs/CHANGELOG.md).
- [x] All: Considered updating the online docs in the [./docs/](/ethereum/execution-spec-tests/blob/main/docs/) directory.
- [x] Tests: All converted JSON/YML tests from [ethereum/tests](/ethereum/tests) have been added to [converted-ethereum-tests.txt](/ethereum/execution-spec-tests/blob/main/converted-ethereum-tests.txt).
- [x] Tests: Included the type and version of evm t8n tool used to locally execute test cases:  e.g., ref with commit hash or geth 1.13.1-stable-3f40e65.
- [x] Tests: Ran `mkdocs serve` locally and verified the auto-generated docs for new tests in the [Test Case Reference](https://ethereum.github.io/execution-spec-tests/main/tests/) are correctly formatted.

### CODE REVIEW

**Comment by winsvega** [comment]
let me check

**Comment by winsvega** [comment]
it still puts beacon contract in blockchain tests that are automatically filled for cancun

**Comment by marioevz** [comment]
> it still puts beacon contract in blockchain tests that are automatically filled for cancun (those that do unrelated stuff to beacon root)

For the blockchain tests it should be fine right? It was the state tests where the issue was.

**Comment by winsvega** [comment]
so a state test in bc form will still have it inserted into pre?

**Review by winsvega — APPROVED** [review]

**Pull request merged**
