### PR TITLE
chore(forks): generate fixtures with the Paris network name

### LINKED ISSUE #469: generate tests with Paris keyword instead of Merge
lets follow the standard

Fixtures generated for Paris still use the network name "Merge" instead of "Paris". 

For example:
```
fill tests/istanbul/eip1344_chainid/test_chainid.py::test_chainid[fork_Paris-blockchain_test] --output fixtures/
```
generates a json file with the network name set to "Merge":
```
grep network fixtures/blockchain_tests/istanbul/eip1344_chainid/chainid/chainid.json 
# ->        "network": "Merge",
```

### PR DESCRIPTION
**Pull request by raxhvl**
## 🗒️ Description
closes #469
## 🔗 Related Issues
#469 
## ✅ Checklist
- [x] All: Set appropriate labels for the changes.
- [x] All: Considered squashing commits to improve commit history.
- [ ] All: Added an entry to [CHANGELOG.md](/ethereum/execution-spec-tests/blob/main/docs/CHANGELOG.md).
- [x] All: Considered updating the online docs in the [./docs/](/ethereum/execution-spec-tests/blob/main/docs/) directory.
- [x] Tests: All converted JSON/YML tests from [ethereum/tests](/ethereum/tests) have been added to [converted-ethereum-tests.txt](/ethereum/execution-spec-tests/blob/main/converted-ethereum-tests.txt).
- [x] Tests: Included the type and version of evm t8n tool used to locally execute test cases:  e.g., ref with commit hash or geth 1.13.1-stable-3f40e65.
- [x] Tests: Ran `mkdocs serve` locally and verified the auto-generated docs for new tests in the [Test Case Reference](https://ethereum.github.io/execution-spec-tests/main/tests/) are correctly formatted.

Changelog NOT updated because of the trivial nature.

### CODE REVIEW

**Review by spencer-tb — COMMENTED** [review]
Thanks Raxhvl, this is an addition I'd personally love - but it requires that client teams make this change on their end when consuming the test fixture.

Currently geth responds with:
```
unsupported fork "Paris"
```
when running:
```
evm blocktest
```
against the appropriate json test fixture containing the test with the "Paris" network name. 

I haven't checked but this is likely a very easy change for them! I can have a look :)

**Comment by raxhvl** [comment]
Sweet. I guess we wait for them then.

**Comment by spencer-tb** [comment]
Okay so its an quick change on Geth: https://github.com/ethereum/go-ethereum/compare/master...spencer-tb:go-ethereum:tests/init

I want to make sure the tests work when running them on a fully instantiated client in hive:
https://github.com/ethereum/hive/tree/master/simulators/ethereum/pyspec

Assuming the latter, I'd say merging this in is good to go. Ideally we have some PRs ready for each client before our next release.

**Review by marioevz — APPROVED** [review]
Thanks!

**Pull request merged**
