### PR TITLE
chore: Updated fork name from Merge -> Paris

### LINKED ISSUE #362: chore: Update the "Merge" fork name to "Paris" within the repo
Simple renaming. If we have the correct fork names throughout, it makes sense to me that Merge -> Paris.

### PR DESCRIPTION
**Pull request by MukulKolpe**
## 🗒️ Description

Updated Fork name from "Merge" to "Paris" within the repository.
## 🔗 Related Issues

Fixes #362
## ✅ Checklist
- [x] All: Set appropriate labels for the changes.
- [x] All: Considered squashing commits to improve commit history.
- [x] All: Added an entry to [CHANGELOG.md](/ethereum/execution-spec-tests/blob/main/docs/CHANGELOG.md).
- [x] All: Considered updating the online docs in the [./docs/](../docs/) directory.
- [x] Tests: Included the type and version of evm t8n tool used to locally execute test cases:  e.g., ref with commit hash or geth 1.13.1-stable-3f40e65.
- [x] Tests: Ran `mkdocs serve` locally and verified the auto-generated docs for new tests in the [Test Case Reference](https://ethereum.github.io/execution-spec-tests/main/tests/) are correctly formatted.

### CODE REVIEW

**Review by marioevz — COMMENTED** [review]
This looks great, thanks for helping out with this!

There is still an issue with this change and it's that the transition tool, the tool we call to perform the evm execution of the transactions included in the block, it still expects "Merge" when receiving the fork name for Paris.

It would be a bit messy to try to do this with the rest of the code as is right now, mainly because we don't have the code in place to handle such discrepancy, but I've opened this PR https://github.com/ethereum/execution-spec-tests/pull/366 that implements exactly that.

I would:
- Wait until https://github.com/ethereum/execution-spec-tests/pull/366 is merged
- Rebase your branch on top of main

And then we should be able to merge your contribution :)

**Comment by MukulKolpe** [comment]
Sounds great! I've incorporated the suggested modifications. Thanks a lot for your help.

**Comment by marioevz** [comment]
Hey @MukulKolpe thanks for the changes!
Could you do a couple more things please?
- Rebase to the latest `main` branch: There are some conflicts that will need to be solved. Once done, you can force-push to your branch and github should pick it up immediately.
- Run `tox -e framework`: There seem to be a couple of failing unit tests at the moment, but could be that they are fixed after the rebase.

**Comment by marioevz** [comment]
> Should I add an entry in the [CHANGELOG.md](https://github.com/ethereum/execution-spec-tests/blob/main/docs/CHANGELOG.md)?

Yes please!

**Review by spencer-tb — COMMENTED** [review]
Thanks for helping out on this :) 

All looks good to me - apart from the folder name:
```
tests/merge/... -> tests/paris/...
```

And then the changelog!

**Review by marioevz — APPROVED** [review]
Fantastic! Thank you so much for this!

**Comment by MukulKolpe** [comment]
Thanks @spencer-tb, @marioevz!!

**Comment by spencer-tb** [comment]
Thanks! @MukulKolpe

**Pull request merged**
