### PR TITLE
feat(docs): update for solc 0.8.23 support

### PR DESCRIPTION
**Pull request by richardgreg**
## 🗒️ Description

Updated framework tests and docs for solc 0.8.23
## 🔗 Related Issues

#345
## ✅ Checklist
- [x] All: Set appropriate labels for the changes.
- [x] All: Considered squashing commits to improve commit history.
- [x] All: Added an entry to [CHANGELOG.md](/ethereum/execution-spec-tests/blob/main/docs/CHANGELOG.md).
- [x] All: Considered updating the online docs in the [./docs/](../docs/) directory.
- [x] Tests: Included the type and version of evm t8n tool used to locally execute test cases:  e.g., ref with commit hash or geth 1.13.1-stable-3f40e65.
- [x] Tests: Ran `mkdocs serve` locally and verified the auto-generated docs for new tests in the [Test Case Reference](https://ethereum.github.io/execution-spec-tests/main/tests/) are correctly formatted.

### CODE REVIEW

**Comment by richardgreg** [comment]
@danceratopz This is a work in progress. I began by looking at your changes for solc 0.8.22 and replicating them. Making edits to the README and quickstart seemed straightforward. For the others like `chore(ci): run macos tox with solc 0.8.22`, and `chore(fw): enable fw tests in (test_code.py) with solc 0.8.23-dev` I wanted your opinion on replicating it like for like with a version bump.

Regarding `--yul-optimizations sequence` the implementation is to be done in `yul.py` right? I'm also wondering what the issue is and the logic needed to solve it. Did adding an empty ``--yul-optimizations` lead to an error?

**Comment by danceratopz** [comment]
> @danceratopz This is a work in progress. I began by looking at your changes for solc 0.8.22 and replicating them. Making edits to the README and quickstart seemed straightforward.

Thanks a lot for making a start on this!

> For the others like `chore(ci): run macos tox with solc 0.8.22`, and `chore(fw): enable fw tests in (test_code.py) with solc 0.8.23-dev` I wanted your opinion on replicating it like for like with a version bump.

Regarding these commits (btw, you can link commit hashes in PR comments for convenience :slightly_smiling_face:):
- `chore(fw): enable fw tests in (test_code.py) with solc 0.8.23-dev`, https://github.com/ethereum/execution-spec-tests/pull/340/commits/d8c63bd7b6f71efa8cd6e9d5683b1e0ebe174a08: Enabling the "next" version here (this would be `0.8.24` in this PR) allows us (or the Solidity Team) to execute the framework tests (and therefore `tox`) using the current development version of solc, i.e.:
    ```
    pytest -c pytest-framework.ini 
    ```
    I typically clone the solidity repo and build from `develop` to test this, see the [docs](https://docs.soliditylang.org/en/latest/installing-solidity.html#command-line-build). Let me know if you have any issues.
- `chore(ci): run macos tox with solc 0.8.22` https://github.com/ethereum/execution-spec-tests/pull/340/commits/c86cdfab210d0f79749b1a8b518d491ff5aed646: I think I'd change this entry:
    https://github.com/ethereum/execution-spec-tests/blob/8c7cb87cee733a76a08170e666428a569f840bd8/.github/workflows/test.yaml#L16-L20
    to run with `0.8.23`, for now. Our matrix combinations are not exhaustive, but try to cover most configs, although not in isolation. We'll probably have to re-think this strategy at some point or potentially deprecate older versions of solc.

> Regarding `--yul-optimizations sequence` the implementation is to be done in `yul.py` right? I'm also wondering what the issue is and the logic needed to solve it. Did adding an empty ``--yul-optimizations` lead to an error?

The task here is to work out whether we're doing everything we can to disable the optimizations `solc` performs when compiling Yul code (and whether anything has changed in this regard in 0.8.23). I've never tried `--yul-optimizations`; I just spotted it in the release notes and wondered whether we can improve the current situation in execution-spec-tests. 

At the moment these are the options we use:
https://github.com/ethereum/execution-spec-tests/blob/8c7cb87cee733a76a08170e666428a569f840bd8/src/ethereum_test_tools/code/yul.py#L75-L79
If `0.8.23` makes it easier to disable optimizations, it would be nice to add this. We would only add it to solc for versions `>=0.8.23` obviously though.

If you're interested, feel free to dig in. If not, zero worries, we can add this to a separate issue or I can have a look :slightly_smiling_face:.

**Comment by richardgreg** [comment]
I've pushed updates. I'd like to dig into the yul optimization task but as a separate task. From what you've stated the solution seems like an if statement that checks if the version is greater than or equal to 0.8.23 and adds `--yul-optimizations` as a default arg. My knowledge of the program is still superficial so I'd like to use the opportunity to explore the program deeply.

**Review by danceratopz — APPROVED** [review]
Thanks, looks good to me! I just fixed up black and added a changelog entry. 

Also thanks for adding #395.

**Pull request merged**
