### PR TITLE
docs: improve docstrings for generated doc

### PR DESCRIPTION
**Pull request by danceratopz**
This PR:

1. Introduces an (optional) docstring format for test modules to produce admonitions in the generated doc:
```python
"""
abstract: test module title/overview
    detailed description 

note: Test cases ported from:
    links to original tests
"""
```

2. Cleans up the docstrings in tests/ to remove any obvious mal-formatted doc and ensure URLs are linked.

3. Does one **non-doc** related change: Runs the `tests/eips/test_eip3651.py::test_warm_coinbase_gas_usage`  tests additionally for Merge - perhaps this is too much @marioevz?

4. Modifies the `docs/gen_test_case_reference.py` to:
    - Always make `__init__.py` the leaf's `index.md`.
    - To include `--fork=DEV_FORK` for top-level index.md and for any test module under a dev branch folder (ready for the upcoming fork folder restructure).

Todo:
- [x] Clean-up 4844 test case docstrings - @marioevz / @spencer-tb could you please do this (can be a separate PR)?

Preview (**manually deployed**) available here:
https://danceratopz.github.io/execution-spec-tests/tests/

### CODE REVIEW

**Comment by marioevz** [comment]
Added 4844, except for blobhash :+1: 

I'm not entirely sure why it looks like I rebased, but I don't think I did, at least on purpose.

**Comment by danceratopz** [comment]
Added a few minor doc changes and modified the docs/gen_test_case_reference.py to:
- Always make `__init__.py` the nav entry's index.md.
- To include --fork=DEV_FORK for top-level index.md and for any test module under a dev branch folder (ready for the upcoming fork folder restructure).

Updated the preview:
https://danceratopz.github.io/execution-spec-tests/tests/

**Comment by danceratopz** [comment]
Can we remove `tests/eips/eip4844/README.md` now? Or does it still have relevant doc not included in the test modules? We can leave it if it's up-to-date/relevant!

It's currently included as:
grafik

**Comment by marioevz** [comment]
> Can we remove `tests/eips/eip4844/README.md` now? Or does it still have relevant doc not included in the test modules? We can leave it if it's up-to-date/relevant!
> 
> It's currently included as: grafik

I removed it in the latest commit, we still can recover it from the commit history if necessary!

I think we can merge now?

**Review by spencer-tb — APPROVED** [review]
LGTM!!

**Review by marioevz — APPROVED** [review]

**Pull request merged**
