### PR TITLE
chore(refactor): blockchain test hive fixture format (include `params`)

### PR DESCRIPTION
**Pull request by marioevz**
## 🗒️ Description
Refactors the blockchain hive fixture format to match the execution-apis format (see https://github.com/ethereum/execution-apis/blob/main/src/engine/prague.md#request).

Namely, the format now directly contains the `params` field mentioned in the specification, and should be possible to simply relay this field to the execution client during testing.

These changes have been integrated to work with `consume engine`. Additionally all references to "blockchain hive" or "blockchain_tests_hive" etc has been changed to "blockchain_engine" or "blockchain_tests_engine". As in the future we will have many more hive related fixture formats.

## 🔗 Related Issues
None

## ✅ Checklist
- [x] All: Set appropriate labels for the changes.
- [x] All: Considered squashing commits to improve commit history.
- [x] All: Added an entry to [CHANGELOG.md](/ethereum/execution-spec-tests/blob/main/docs/CHANGELOG.md).
- [x] All: Considered updating the online docs in the [./docs/](/ethereum/execution-spec-tests/blob/main/docs/) directory.
- [x] Tests: All converted JSON/YML tests from [ethereum/tests](/ethereum/tests) have been added to [converted-ethereum-tests.txt](/ethereum/execution-spec-tests/blob/main/converted-ethereum-tests.txt).
- [x] Tests: A PR with removal of converted JSON/YML tests from [ethereum/tests](/ethereum/tests) have been opened.
- x ] Tests: Included the type and version of evm t8n tool used to locally execute test cases:  e.g., ref with commit hash or geth 1.13.1-stable-3f40e65.
- [x] Tests: Ran `mkdocs serve` locally and verified the auto-generated docs for new tests in the [Test Case Reference](https://ethereum.github.io/execution-spec-tests/main/tests/) are correctly formatted.

### CODE REVIEW

**Comment by spencer-tb** [comment]
Super nice! I am just rebasing consume engine on top of main after the `ethereum_test_tools` refactor :)

After we merge consume engine, lets integrate and test and get this merged too

**Comment by spencer-tb** [comment]
What do you think about calling the `BlockchainHiveFixtures` -> `EngineAPIFixtures` or `EngineNewPayloadFixturse`? Or similar. The former suites better for me as they pertain to more than just the single `engine_newPayloadVX` methods

My assumption is that we will never use them in hive directly again, and that they specifically test the EngineAPI

**Comment by marioevz** [comment]
> What do you think about calling the `BlockchainHiveFixtures` -> `EngineAPIFixtures` or `EngineNewPayloadFixturse`? Or similar. The former suites better for me as they pertain to more than just the single `engine_newPayloadVX` methods
> 
> My assumption is that we will never use them in hive directly again, and that they specifically test the EngineAPI

I see the point now, in that case maybe `BlockchainEngineFixture`?

**Review by spencer-tb — APPROVED** [review]
I changed the naming and integrated the changes with `consume engine`.

I'd try `fill` and `consume` the engine format now before merging :)

**Pull request merged**
